name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone Cuh-KerneL Repository
        run: |
          git clone --depth 1 https://${{ secrets.USERNAME }}:${{ secrets.TOKEN }}@github.com/${{ secrets.USERNAME }}/Cuh-KerneL.git -b fifteenKSU kernel
          cd kernel
          chmod 777 build.sh
          ./build.sh

      - name: Upload Build Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: kernel-build
          path: kernel/output/*  # Adjust this path to match where your build output is stored
