name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Remove existing kernel directory (if it exists)
        run: |
          if [ -d "kernel" ]; then
            echo "Removing existing kernel directory."
            rm -rf kernel
          fi

      - name: Clone Cuh-KerneL Repository
        run: |
          git clone --depth 1 https://github.com/xiihaiqal/kernel_xiaomi_ginkgo.git -b fourteenKSU kernel
          cd kernel
          chmod 777 build.sh
          ./build.sh

      - name: Upload Build Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: kernel-build
          path: kernel/*  # Adjust this path to match where your build output is stored
